config/routes.rb
Rails.application.routes.draw do
  resources :crops
  resources :farms do
    resources :crops do
      get 'select_box', on: :collection
    end
  end
  devise_for :users, :path_prefix => 'login'
  
  get "/home", to: "farms#home", as: :user_home
  
  root to: "farms#home"
  
  resources :transactions
  resources :expenses, controller: 'transactions', type: 'Expense'
  resources :revenues, controller: 'transactions', type: 'Revenue'
  resources :investments, controller: 'transactions', type: 'Investment'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/farm.rb
class Farm < ApplicationRecord
  has_many :farm_users
  has_many :users, through: :farm_users
  has_many :crops
  has_many :transactions
  attr_accessor :email
  
  def sum_transaction(trans_type)
    transactions.where(trans_type: trans_type).sum(:amount)
  end
  
  def calculate_profit
    sum_transaction("Revenue") - sum_transaction("Expense")
  end
  
  def calculate_capital_left
    sum_transaction("Investment") == 0 ? 0.0 : (sum_transaction("Investment") - sum_transaction("Expense"))
  end
  
end

app/controllers/farms_controller.rb
class FarmsController < ApplicationController
  before_action :set_farm, only: [:show, :edit, :update, :destroy]
  before_action :authorize_owner, only: [:new, :edit, :create, :update, :destroy]
  
  def home
    @farms = current_user.farms
  end
  
  # GET /farms
  def index
    @farms = current_user.farms
  end

  # GET /farms/1
  def show
  end

  # GET /farms/new
  def new
    @farm = Farm.new
  end

  # GET /farms/1/edit
  def edit
  end

  # POST /farms
  def create
    @farm = Farm.new(farm_params)

    if @farm.save
      FarmUser.create(farm_id: @farm.id, user_id: current_user.id)
      redirect_to @farm, notice: 'Farm was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /farms/1
  def update
    if @farm.update(farm_params)
      redirect_to @farm, notice: 'Farm was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /farms/1
  # def destroy
  #   @farm.destroy
  #   redirect_to farms_url, notice: 'Farm was successfully destroyed.'
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_farm
      @farm = Farm.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def farm_params
      params.require(:farm).permit(:name, :address, :city, :state, :country)
    end
end

app/helpers/farms_helper.rb
module FarmsHelper
end

app/views/farms/_form.html.haml
= form_for @farm, html: { class: "form form-horizontal farm" } do |f|
  .form-group
    = f.label :name, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :name, class: 'form-control', required: true
    = f.error_span(:name)
  .form-group
    = f.label :address, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :address, class: 'form-control', required: true
    = f.error_span(:address)
  .form-group
    = f.label :city, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :city, class: 'form-control', required: true
    = f.error_span(:city)
  .form-group
    = f.label :state, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :state, class: 'form-control', required: true
    = f.error_span(:state)
  .form-group
    = f.label :country, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :country, class: 'form-control', required: true
    = f.error_span(:country)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil,class: 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")), farms_path, :class => 'btn btn-default'

app/views/farms/edit.html.haml
- model_class = Farm
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/farms/home.html.haml
.row
  - @farms.each do |farm|
    .col-sm-4
      %h2= link_to farm.name, farm_path(farm)
      - ['Expense', 'Revenue', 'Investment'].each do |transaction|
        %p
          Total #{transaction}
          = number_to_indian_currency(farm.sum_transaction(transaction))
      %p
        Total Profit
        = number_to_indian_currency(farm.calculate_profit)
      %p
        Capital Left Over
        = number_to_indian_currency(farm.calculate_capital_left)
      

app/views/farms/index.html.haml
- model_class = Farm
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:address)
      %th= model_class.human_attribute_name(:city)
      %th= model_class.human_attribute_name(:state)
      %th= model_class.human_attribute_name(:country)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @farms.each do |farm|
      %tr
        %td= link_to farm.name, farm_path(farm)
        %td= farm.address
        %td= farm.city
        %td= farm.state
        %td= farm.country
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_farm_path(farm), :class => 'btn btn-default btn-xs'

= link_to t('.new', :default => t("helpers.links.new")), new_farm_path, :class => 'btn btn-primary'

app/views/farms/new.html.haml
- model_class = Farm
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/farms/show.html.haml
- model_class = Farm
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @farm.name
%p
  %strong= model_class.human_attribute_name(:address) + ':'
  %br
  = @farm.address
%p
  %strong= model_class.human_attribute_name(:city) + ':'
  %br
  = @farm.city
%p
  %strong= model_class.human_attribute_name(:state) + ':'
  %br
  = @farm.state
%p
  %strong= model_class.human_attribute_name(:country) + ':'
  %br
  = @farm.country


= link_to t('.back', :default => t("helpers.links.back")), farms_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_farm_path(@farm), :class => 'btn btn-default'