config/routes.rb
Rails.application.routes.draw do
  resources :crops
  resources :farms do
    resources :crops do
      get 'select_box', on: :collection
    end
  end
  devise_for :users, :path_prefix => 'login'
  
  get "/home", to: "farms#home", as: :user_home
  
  root to: "farms#home"
  
  resources :transactions
  resources :expenses, controller: 'transactions', type: 'Expense'
  resources :revenues, controller: 'transactions', type: 'Revenue'
  resources :investments, controller: 'transactions', type: 'Investment'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/crop.rb
class Crop < ApplicationRecord
  
  belongs_to :farm
  has_many :transactions
  
  def life_span
    life_span = (life_span_years.blank? ? "0" : life_span_years.to_s) + " Years "
    life_span = life_span + (life_span_months.blank? ? "0" : life_span_months.to_s) + " Months "
    life_span = life_span + (life_span_days.blank? ? "0" : life_span_days.to_s) + " Days "
    life_span
  end
end

app/controllers/crops_controller.rb
class CropsController < ApplicationController
  before_action :set_crop, only: [:show, :edit, :update, :destroy]
  before_action :set_form_selects, only: [:new, :edit]
  before_action :authorize_owner, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_farms

  # GET /crops
  # GET /crops.json
  def index
    if @farm_ids.empty?
      @crops = []
    else
      @crops = Crop.where('farm_id in (?)', @farm_ids).order(:name)
    end
  end

  # GET /crops/1
  # GET /crops/1.json
  def show
  end
  
  def select_box
    @crops = Crop.where(farm_id: params[:farm_id])
    @model_name = params['model']
    render layout: false
  end

  # GET /crops/new
  def new
    @crop = Crop.new
  end

  # GET /crops/1/edit
  def edit
  end

  # POST /crops
  # POST /crops.json
  def create
    @crop = Crop.new(crop_params)

    respond_to do |format|
      if @crop.save
        format.html { redirect_to @crop, notice: 'Crop was successfully created.' }
        format.json { render :show, status: :created, location: @crop }
      else
        format.html { render :new }
        format.json { render json: @crop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crops/1
  # PATCH/PUT /crops/1.json
  def update
    respond_to do |format|
      if @crop.update(crop_params)
        format.html { redirect_to @crop, notice: 'Crop was successfully updated.' }
        format.json { render :show, status: :ok, location: @crop }
      else
        format.html { render :edit }
        format.json { render json: @crop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crops/1
  # DELETE /crops/1.json
  # def destroy
  #   @crop.destroy
  #   respond_to do |format|
  #     format.html { redirect_to crops_url, notice: 'Crop was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crop
      @crop = Crop.find(params[:id])
    end
    
    def set_farms
      @farm_ids = current_user.farms.collect { |farm| farm.id }
    end
    
    def set_form_selects
      @farms = current_user.farms
      @seasons = [['Summer', 'Summer'], ['Winter', 'Winter'], ['Rainy', 'Rainy']]
      @merasures = [['acre', 'acre'], ['sqft', 'sqft'], ['sqm', 'sqm'], ['hectare', 'hectare'], ['gunta', 'gunta']]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crop_params
      params.require(:crop).permit(:name, :farm_id, :season, :sowing_date, :harvest_date, :area_covered, 
      :covered_area_measure, :life_span_years, :life_span_months, :life_span_days, :description)
    end
end

app/helpers/crops_helper.rb
module CropsHelper
end

app/views/crops/_form.html.haml
= form_for @crop, html: { class: "form form-horizontal crop" } do |f|
  .form-group
    = f.label :name, class: 'control-label col-lg-2'
    .col-lg-6
      = f.text_field :name, class: 'form-control', required: true
    = f.error_span(:name)
  .form-group
    = f.label :farm_id, class: 'control-label col-lg-2'
    .col-lg-4
      = f.select :farm_id, @farms.collect {|p| [ p.name, p.id ] }, { include_blank: true }, class: 'form-control', required: true
    = f.error_span(:farm_id)
  .form-group
    = f.label :season, class: 'control-label col-lg-2'
    .col-lg-6
      = f.select :season, @seasons, class: 'form-control', required: true
    = f.error_span(:season)
  .form-group
    = f.label :sowing_date, class: 'control-label col-lg-2'
    .col-lg-2.datepicker
      = f.text_field :sowing_date, class: 'form-control', required: true, data: {provide: 'datepicker'}
    = f.error_span(:sowing_date)
  .form-group
    = f.label :harvest_date, class: 'control-label col-lg-2'
    .col-lg-2.datepicker
      = f.text_field :harvest_date, class: 'form-control', required: true, data: {provide: 'datepicker'}
    = f.error_span(:harvest_date)
  .form-group
    = f.label :area_covered, class: 'control-label col-lg-2'
    .row
      .col-lg-1
        = f.text_field :area_covered, class: 'form-control', required: true
      .col-lg-1
        = f.select :covered_area_measure, @merasures, class: 'form-control', required: true
    = f.error_span(:area_covered)
  .form-group
    = f.label :life_span, class: 'control-label col-lg-2'
    .row
      .col-lg-1
        = f.text_field :life_span_years, placeholder: 'Years', class: 'form-control', required: true
      .col-lg-1
        = f.text_field :life_span_months, placeholder: 'Months', class: 'form-control', required: true
      .col-lg-1
        = f.text_field :life_span_days, placeholder: 'Days', class: 'form-control', required: true
    = f.error_span(:life_span_years)
  .form-group
    = f.label :description, class: 'control-label col-lg-2'
    .col-lg-6
      = f.text_area :description, class: 'form-control', required: true
    = f.error_span(:description)
  .form-group
    .col-lg-offset-2.col-lg-6
      = f.submit nil,class: 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")), crops_path, :class => 'btn btn-default'

app/views/crops/edit.html.haml
- model_class = Crop
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/crops/index.html.haml
- model_class = Crop
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:farm_id)
      %th= model_class.human_attribute_name(:season)
      %th= model_class.human_attribute_name(:sowing_date)
      %th= model_class.human_attribute_name(:harvest_date)
      %th= model_class.human_attribute_name(:area_covered)
      %th= model_class.human_attribute_name(:life_span)
      %th= model_class.human_attribute_name(:description)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @crops.each do |crop|
      %tr
        %td= link_to crop.name, crop_path(crop)
        %td= link_to crop.farm.name, farm_path(crop.farm)
        %td= crop.season
        %td= crop.sowing_date
        %td= crop.harvest_date
        %td= crop.area_covered.to_s + " " + crop.covered_area_measure
        %td= crop.life_span
        %td= crop.description
        %td
          = link_to t('.show', :default => t("helpers.links.show")), crop_path(crop), :class => 'btn btn-default btn-xs'
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_crop_path(crop), :class => 'btn btn-default btn-xs'

= link_to t('.new', :default => t("helpers.links.new")), new_crop_path, :class => 'btn btn-primary'

app/views/crops/new.html.haml
- model_class = Crop
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/crops/select_box.html.haml
= select_tag "#{@model_name}[crop_id]", options_from_collection_for_select(@crops, "id", "name"), include_blank: true, class: 'form-control', id: "#{@model_name}_crop_id"

app/views/crops/show.html.haml
- model_class = Crop
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @crop.name
%p
  %strong= model_class.human_attribute_name(:farm_id) + ':'
  %br
  = @crop.farm_id
%p
  %strong= model_class.human_attribute_name(:season) + ':'
  %br
  = @crop.season
%p
  %strong= model_class.human_attribute_name(:sowing_date) + ':'
  %br
  = @crop.sowing_date
%p
  %strong= model_class.human_attribute_name(:harvest_date) + ':'
  %br
  = @crop.harvest_date
%p
  %strong= model_class.human_attribute_name(:area_covered) + ':'
  %br
  = @crop.area_covered
%p
  %strong= model_class.human_attribute_name(:covered_area_measure) + ':'
  %br
  = @crop.covered_area_measure
%p
  %strong= model_class.human_attribute_name(:life_span_years) + ':'
  %br
  = @crop.life_span_years
%p
  %strong= model_class.human_attribute_name(:life_span_months) + ':'
  %br
  = @crop.life_span_months
%p
  %strong= model_class.human_attribute_name(:life_span_days) + ':'
  %br
  = @crop.life_span_days
%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @crop.description


= link_to t('.back', :default => t("helpers.links.back")), crops_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_crop_path(@crop), :class => 'btn btn-default'