config/routes.rb
Rails.application.routes.draw do
  resources :crops
  resources :farms do
    resources :crops do
      get 'select_box', on: :collection
    end
  end
  devise_for :users, :path_prefix => 'login'
  
  get "/home", to: "farms#home", as: :user_home
  
  root to: "farms#home"
  
  resources :transactions
  resources :expenses, controller: 'transactions', type: 'Expense'
  resources :revenues, controller: 'transactions', type: 'Revenue'
  resources :investments, controller: 'transactions', type: 'Investment'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]
  before_action :set_form_selects, only: [:new, :edit, :create, :update]
  before_action :set_trans_type, :set_farms
  before_action :authorize_owner, only: [:new, :edit, :create, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    if @farm_ids.empty?
      @transactions = []
      @transaction_sum = 0
    else
      @transactions = trans_type_class.where('farm_id in (?)', @farm_ids).order('transaction_date desc')
      @transaction_sum = @transactions.sum(:amount)
    end
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = trans_type_class.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = trans_type_class.new(transaction_params)
    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: "#{trans_type_class} was successfully created." }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: "#{trans_type_class} was successfully updated." }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: "#{trans_type_class} was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = trans_type_class.find(params[:id])
    end
    
    def set_farms
      @farm_ids = current_user.farms.collect { |farm| farm.id }
    end
    
    def set_trans_type
      @trans_type = trans_type
    end

    def trans_type
      Transaction.trans_types.include?(params[:type]) ? params[:type] : "Transaction"
    end
    
    def trans_type_class
      trans_type.constantize
    end
    
    def set_form_selects
      @farms = current_user.farms
      @methods = [['Cash', 'Cash'], ['Cheque', 'Cheque'], ['Internet Transfer', 'Internet']]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(trans_type.underscore.to_sym).permit(:reason, :location, :bill_image_path, 
      :description, :debit_credit, :amount, :trans_type, :farm_id, :crop_id, :transaction_date,
      :transaction_method, :identifier, :created_by, :updated_by, :place_of_transaction, :bill_details)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.haml
= form_for @transaction, html: { class: "form form-horizontal transaction" } do |f|
  = render '/errors', object: @transaction
  
  - if @trans_type != "Transaction"
    = f.hidden_field :trans_type, value: @trans_type
  - if @trans_type == "Expense"
    .form-group
      = f.label :bill_details, class: 'control-label col-lg-2'
      .col-lg-10
        = f.text_field :bill_details, class: 'form-control', required: false
      = f.error_span(:bill_details)
  .form-group
    = f.label :transaction_date, class: 'control-label col-lg-2'
    .col-lg-2.datepicker
      = f.text_field :transaction_date, class: 'form-control  .date-picker', required: true, data: {provide: 'datepicker'}
    = f.error_span(:transaction_date)
  .form-group
    = f.label :amount, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :amount, class: 'form-control', required: true
    = f.error_span(:amount)
  .form-group
    = f.label :place_of_transaction, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :place_of_transaction, class: 'form-control', required: false
    = f.error_span(:place_of_transaction)
  .form-group
    = f.label :transaction_method, class: 'control-label col-lg-2'
    .col-lg-4
      = f.select :transaction_method, @methods, { include_blank: true }, class: 'form-control', required: true
    = f.error_span(:transaction_method)
  .form-group
    %label{ class: 'control-label col-lg-2'}
      Cheque No./Transfer Id
    .col-lg-10
      = f.text_field :identifier, class: 'form-control', required: false
    = f.error_span(:identifier)
  .form-group
    = f.label :farm_id, class: 'control-label col-lg-2'
    .col-lg-4
      = f.select :farm_id, @farms.collect {|p| [ p.name, p.id ] }, { include_blank: true }, class: 'form-control', required: true
    = f.error_span(:farm_id)
  .form-group
    = f.label :crop_id, class: 'control-label col-lg-2'
    #crop_select.col-lg-4
      = f.select :crop_id, [], { include_blank: true }, class: 'form-control', required: false
    = f.error_span(:farm_id)
  .form-group
    %label{ class: 'control-label col-lg-2'}
      Other Reason
    .col-lg-10
      = f.text_field :reason, class: 'form-control', required: false
    = f.error_span(:reason)
  .form-group
    = f.label :description, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_area :description, class: 'form-control', required: false
    = f.error_span(:description)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil,class: 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")), transactions_path(type: @trans_type), :class => 'btn btn-default'

app/views/transactions/edit.html.haml
- model_class = @trans_type.constantize
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/transactions/index.html.haml
- model_class = @trans_type.constantize
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
  %h4= "Total: " + number_to_indian_currency(@transaction_sum).to_s
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:transaction_date)
      %th= model_class.human_attribute_name(:amount)
      %th= model_class.human_attribute_name(:place_of_transaction)
      %th= model_class.human_attribute_name(:transaction_method)
      %th Cheque/Transfer Id
      %th= model_class.human_attribute_name(:reason)
      %th= model_class.human_attribute_name(:farm_id)
      %th= model_class.human_attribute_name(:crop_id)
  %tbody
    - @transactions.each do |transaction|
      %tr
        %td= link_to transaction.transaction_date, transaction_path(transaction, type: @trans_type)
        %td= number_to_indian_currency(transaction.amount)
        %td= transaction.place_of_transaction
        %td= transaction.transaction_method
        %td= transaction.identifier
        %td= transaction.reason
        %td= transaction.farm.try(:name)
        %td= transaction.crop.try(:name)
        
= link_to t('.new', :default => t("helpers.links.new")), new_transaction_path(type: @trans_type), :class => 'btn btn-primary'

app/views/transactions/new.html.haml
- model_class = @trans_type.constantize
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/transactions/show.html.haml
- model_class = @trans_type.constantize
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:bill_details) + ':'
  = @transaction.bill_details
%p
  %strong= model_class.human_attribute_name(:transaction_date) + ':'
  = @transaction.transaction_date
%p
  %strong= model_class.human_attribute_name(:amount) + ':'
  = @transaction.amount
%p
  %strong= model_class.human_attribute_name(:place_of_transaction) + ':'
  = @transaction.place_of_transaction
%p
  %strong= model_class.human_attribute_name(:transaction_method) + ':'
  = @transaction.transaction_method
%p
  %strong Cheque/Transfer Id:
  = @transaction.identifier
%p
  %strong= model_class.human_attribute_name(:place_of_transaction) + ':'
  = @transaction.place_of_transaction
%p
  %strong= model_class.human_attribute_name(:farm_id) + ':'
  = @transaction.farm.try(:name)
%p
  %strong= model_class.human_attribute_name(:crop_id) + ':'
  = @transaction.crop.try(:name)
%p
  %strong= model_class.human_attribute_name(:reason) + ':'
  = @transaction.reason
%p
  %strong= model_class.human_attribute_name(:description) + ':'
  = @transaction.description


= link_to t('.back', :default => t("helpers.links.back")), transactions_path(type: @trans_type), :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_transaction_path(@transaction), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), transaction_path(@transaction), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'